spring:
  application:
    name: consumer-movie-ribbon
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    prefer-ip-address: true

