spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaofanting/spring-cloud-config-repo/
  application:
    name: config-server-eureka
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:9000/eureka